name: Release

env:
  solution-path: csharp/OpenSvip.sln
  cli-proj-path: csharp/Console
  plugin-proj-path: csharp/Plugins
  dotnet-version: "7.0"
  plugins: |
    Midi
    SynthV


on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  build-exe:
    name: Build executable and plugins for ${{ matrix.platform[0] }}
    runs-on: ${{ matrix.platform[0] }}
    strategy:
      matrix:
        platform:
          - [windows-latest, win-x64]
          - [macos-latest, osx-arm64]
          - [ubuntu-latest, linux-x64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-version }}

    - name: Create Artifact Directory
      run: mkdir artifact

    # - name: Restore Denepndicies
    #   run: dotnet restore ${{ env.solution-path }} \
    #         -r ${{ matrix.platform[1] }}

    - name: Build CLI
      shell: bash
      run: |
        dotnet publish ${{ env.cli-proj-path }} \
          -c Release \
          -r ${{ matrix.platform[1] }} \
          --self-contained \
          -p:PublishSingleFile=true \
          -p:PublishReadyToRun=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:PublishDir=out/${{ matrix.platform[1] }}/

        zip -r artifact/OpenSvip-Console-${{ matrix.platform[1] }}.zip ${{ env.cli-proj-path }}/out/${{ matrix.platform[1] }}/* -x "*.pdb"

    - name: Build Plugins
      shell: bash
      run: |
        set -e

        for plugin in ${{ env.plugins }}; do
          dotnet build ${{ env.plugin-proj-path }}/$plugin \
            -c Release \
            -r ${{ matrix.platform[1] }} \
            --no-self-contained \
            -p:PublishDir=out/${{ matrix.platform[1] }}/

          zip -r artifact/OpenSvip-Plugin-$plugin-${{ matrix.platform[1] }}.zip ${{ env.plugin-proj-path }}/$plugin/out/${{ matrix.platform[1]}}/* -x "*.pdb"
        done

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: artifact/*.zip
